export const tableDummyData = [{"property_name":"Wally Betje","category":"Gwendolin Krimmer","sub_category":"Brody Glantz","edit":null,"delete":null},
  {"property_name":"Evelina Sore","category":"Domingo Ashurst","sub_category":"Tiebold Cleeton","edit":null,"delete":null},
  {"property_name":"Maressa Seekings","category":"Etty Kinsman","sub_category":"Skipp Qualtrough","edit":null,"delete":null},
  {"property_name":"Sophia Willson","category":"Carmen McGaw","sub_category":"Yetty Dodgson","edit":null,"delete":null},
  {"property_name":"Harmonie MacLise","category":"Irvine Springell","sub_category":"Orton Bizzey","edit":null,"delete":null},
  {"property_name":"Terese Jeratt","category":"Gan Wollaston","sub_category":"Katharyn Grigorescu","edit":null,"delete":null},
  {"property_name":"Mira Faircliffe","category":"Quintin Backe","sub_category":"Larina Bessell","edit":null,"delete":null},
  {"property_name":"Andrea Matherson","category":"Leoline Kundt","sub_category":"Shanan Simnor","edit":null,"delete":null},
  {"property_name":"Hi McEwen","category":"Ryann Goldberg","sub_category":"Ralph Shawell","edit":null,"delete":null},
  {"property_name":"Dierdre Carrabot","category":"Gaile Fowells","sub_category":"Armin Messenger","edit":null,"delete":null},
// {"property_name":"Helena Inge","category":"Katti Epinay","sub_category":"Ravi De Blasio","edit":null,"delete":null},
// {"property_name":"Kienan Isacke","category":"Alasdair Pidgeley","sub_category":"Cloris Le Prevost","edit":null,"delete":null},
// {"property_name":"Karalynn Ritchard","category":"Mariya McIlwrath","sub_category":"Debera Lambourne","edit":null,"delete":null},
// {"property_name":"Gabrielle Snowden","category":"Georgie De La Hay","sub_category":"Mirella Wakeham","edit":null,"delete":null},
// {"property_name":"Edyth Conechie","category":"Idette Glanders","sub_category":"Debera Ghiron","edit":null,"delete":null},
// {"property_name":"Grant Guyton","category":"Regan Froom","sub_category":"Alec Kaemena","edit":null,"delete":null},
// {"property_name":"Tootsie Clinnick","category":"Michaelina Bulgen","sub_category":"Antoine Hardwidge","edit":null,"delete":null},
// {"property_name":"Lura Bradman","category":"Andi Tampin","sub_category":"Gilles Phlippi","edit":null,"delete":null},
// {"property_name":"Bendix Conyer","category":"Jodie Towriss","sub_category":"Ronny Waiting","edit":null,"delete":null},
// {"property_name":"Angele Dubber","category":"Gustie Grabbam","sub_category":"Trudy Salack","edit":null,"delete":null}
]